// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: engine/api/v1/match.proto

package enginepb

import (
	v1 "exchange/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchType int32

const (
	MatchType_MATCH_TYPE_UNDEFINED      MatchType = 0
	MatchType_ORDER_FULFILLED           MatchType = 1
	MatchType_ORDER_PARTIALLY_FULFILLED MatchType = 2
)

// Enum value maps for MatchType.
var (
	MatchType_name = map[int32]string{
		0: "MATCH_TYPE_UNDEFINED",
		1: "ORDER_FULFILLED",
		2: "ORDER_PARTIALLY_FULFILLED",
	}
	MatchType_value = map[string]int32{
		"MATCH_TYPE_UNDEFINED":      0,
		"ORDER_FULFILLED":           1,
		"ORDER_PARTIALLY_FULFILLED": 2,
	}
)

func (x MatchType) Enum() *MatchType {
	p := new(MatchType)
	*p = x
	return p
}

func (x MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_api_v1_match_proto_enumTypes[0].Descriptor()
}

func (MatchType) Type() protoreflect.EnumType {
	return &file_engine_api_v1_match_proto_enumTypes[0]
}

func (x MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchType.Descriptor instead.
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return file_engine_api_v1_match_proto_rawDescGZIP(), []int{0}
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MakerOrder  *v1.Order `protobuf:"bytes,1,opt,name=maker_order,json=makerOrder,proto3" json:"maker_order,omitempty"`
	MatchType   MatchType `protobuf:"varint,2,opt,name=match_type,json=matchType,proto3,enum=exchange.engine.api.v1.MatchType" json:"match_type,omitempty"`
	VolumeTaken uint64    `protobuf:"varint,3,opt,name=volume_taken,json=volumeTaken,proto3" json:"volume_taken,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_api_v1_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_engine_api_v1_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_engine_api_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetMakerOrder() *v1.Order {
	if x != nil {
		return x.MakerOrder
	}
	return nil
}

func (x *Match) GetMatchType() MatchType {
	if x != nil {
		return x.MatchType
	}
	return MatchType_MATCH_TYPE_UNDEFINED
}

func (x *Match) GetVolumeTaken() uint64 {
	if x != nil {
		return x.VolumeTaken
	}
	return 0
}

var File_engine_api_v1_match_proto protoreflect.FileDescriptor

var file_engine_api_v1_match_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x0a,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0a, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x61, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x54, 0x61, 0x6b, 0x65, 0x6e, 0x2a,
	0x59, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x46, 0x55, 0x4c, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x4c, 0x59, 0x5f, 0x46,
	0x55, 0x4c, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x42, 0x21, 0x5a, 0x1f, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_api_v1_match_proto_rawDescOnce sync.Once
	file_engine_api_v1_match_proto_rawDescData = file_engine_api_v1_match_proto_rawDesc
)

func file_engine_api_v1_match_proto_rawDescGZIP() []byte {
	file_engine_api_v1_match_proto_rawDescOnce.Do(func() {
		file_engine_api_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_api_v1_match_proto_rawDescData)
	})
	return file_engine_api_v1_match_proto_rawDescData
}

var file_engine_api_v1_match_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engine_api_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engine_api_v1_match_proto_goTypes = []interface{}{
	(MatchType)(0),   // 0: exchange.engine.api.v1.MatchType
	(*Match)(nil),    // 1: exchange.engine.api.v1.Match
	(*v1.Order)(nil), // 2: exchange.api.v1.Order
}
var file_engine_api_v1_match_proto_depIdxs = []int32{
	2, // 0: exchange.engine.api.v1.Match.maker_order:type_name -> exchange.api.v1.Order
	0, // 1: exchange.engine.api.v1.Match.match_type:type_name -> exchange.engine.api.v1.MatchType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engine_api_v1_match_proto_init() }
func file_engine_api_v1_match_proto_init() {
	if File_engine_api_v1_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_api_v1_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_api_v1_match_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_api_v1_match_proto_goTypes,
		DependencyIndexes: file_engine_api_v1_match_proto_depIdxs,
		EnumInfos:         file_engine_api_v1_match_proto_enumTypes,
		MessageInfos:      file_engine_api_v1_match_proto_msgTypes,
	}.Build()
	File_engine_api_v1_match_proto = out.File
	file_engine_api_v1_match_proto_rawDesc = nil
	file_engine_api_v1_match_proto_goTypes = nil
	file_engine_api_v1_match_proto_depIdxs = nil
}
